### ISSUE TITLE
Rate limiting and DDoS avoidance

### ISSUE THREAD

**Issue by fiestajetsam** [fiestajetsam/I-D#1]
As was suggested on [the mailing list](https://mailarchive.ietf.org/arch/msg/ntp/1IJuu-VTIJrDp_TMpRW3bIfNsZ4/).

These two have something in common in my mind, but may end up being split up editorially. Also:

* History
* Random Blocking
* Prevention of amplification
  * Request extensions must be as large as replies

**Comment by sa0mad** [comment]
The amplification attack was possible only because of the UDP based management traffic. Because it was UDP based, setting incorrect source IP address worked as means to create an attack and only then the ability to create larger packets enabled amplification of attack. However, if the management requests was TCP based, the scale-up of reply does not become an issue. So, the amplification itself is not the issue, but the ability to redirect it. Putting a restriction on reply sizes is ill-advised general principle, it needs to be tied to ability to redirect that comes with UDP. For such management traffic, there is no reason it could not use TCP. Similarly, there is no reason it could not use TLS to further help to secure it. The unauthorized redirect-unsafe UDP management traffic was the cause of the problem. As we look forward, we should correctly plug the issue without unnecesarily limit what other things we can do. Being able to poll state of servers has immense value, and should not be ruled out this way.

**Comment by fiestajetsam** [comment]
In c9aaf20365f8d95d (which will appear in -02) I have included a requirement which came from ITP (#9) for servers to transmit to clients to reduce their update intervals, this should cover rate limiting where clients are well behaved and not malicious or misconfigured; what should be left now is placing some additional requirements to cover malicious scenarios however those might not be so obvious until I have done something of a threat model where DDoS is an obvious risk that will be covered.

**Comment by fiestajetsam** [comment]
In the initial threat model I have written up (027df73), I've explicitly covered DDoS as a threat and listed out some mitigations - I'm unsure if requiring the removal of mode 7 is the right approach, but rather focusing on what causes the amplification (the factor between request/response sizes). Given I can't really think of any other ways to address this in spec that are appropriate, I'll close this for now.

**Comment by sa0mad** [comment]
Those methods is not as effective as a rate limit, if the mode 7 is to be enable at all.
